employeeData/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :employees
  root 'employees#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

employeeData/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

employeeData/app/models/employee.rb
class Employee < ApplicationRecord

    validates :name, presence: true
    validates :salary, presence: true
    validates :DOB, presence: true
    validates :designation, presence: true
end
 

employeeData/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

employeeData/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	
	def show
		@employee = Employee.find(params[:id])
	end
	def new
		@employee = Employee.new
	end
	def index
	#	binding.pry
		@employees = Employee.all
	end
	def update
		@employee = Employee.find(params[:id])
		if @employee.update(employee_params)
		    redirect_to @employee
	    else
	    	render 'edit'
	    end
	end

	def create
		@employee = Employee.new(employee_params)
		 if @employee.save
		  redirect_to @employee
		 else
		 	render 'new'
		 end
	end
	def edit
		@employee = Employee.find(params[:id])
	end
	def destroy
		@employee = Employee.find(params[:id])
		@employee.destroy
		redirect_to employees_path
	end
	private
		def employee_params
			
			params.require(:employee).permit(:name, :DOB, :salary, :designation)
		end

end

employeeData/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

employeeData/app/helpers/application_helper.rb
module ApplicationHelper
end

employeeData/app/helpers/employees_helper.rb
module EmployeesHelper
end

employeeData/app/helpers/welcome_helper.rb
module WelcomeHelper
end

employeeData/app/views/employees/edit.html.erb
<%= form_with(model: @employee, local: true) do |form| %>
 
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this data from being saved:
      </h2>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <h1>Update employee data</h1>
<p>
<%= form.label :Name %><br>
<%= form.text_field :name %>
</p>
<p>
<%= form.label :DOB %><br>
<%= form.text_field :DOB %>
</p>
<p>
<%= form.label :salary %><br>
<%= form.text_field :salary %>
</p>
<p>
<%= form.label :designation %><br>
<%= form.text_field :designation %>
</p>
<%= form.submit %>
<% end %>
<%= link_to 'Back', employees_path %>

employeeData/app/views/employees/index.html.erb
<h1>All employee detail</h1>
<%= link_to 'new employee',new_employee_path %>
<table>
	<tr>
		<th>employee name</th>
		<th>date of birth</th>
		<th>salary</th>
		<th>designation</th>
		<th colspan="3">
	</tr>
	
	<% @employees.each do |employee| %>
	<tr>
		<td><%= employee.name %></td>
		<td><%= employee.DOB %></td>
		<td><%= employee.salary %></td>
		<td><%= employee.designation %></td>
		<td><%= link_to 'show',employee_path(employee)%>
		<td><%= link_to  'edit',edit_employee_path(employee)%>
		<td><%= link_to 'Destroy', employee_path(employee),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
	</tr>
	<% end %>
</table>

employeeData/app/views/employees/new.html.erb
<%= javascript_include_tag 'new' %>
<%= stylesheet_link_tag "style" %>
<div class="login-box">
<%= form_with scope: :employee, url: employees_path, model: @post, :html => {:id => "reg"}, local: true do |form| %>

<h1><center><b>Employee data</b></center></h1>


<table align="center">
	<tr>

		<td><%= form.label :Name  %></td>
		<td><%= form.text_field :name, id:"name" %></td>
		<td id="error"></td>
	</tr>
	<tr>
		<td><%= form.label :DOB %></td>
		<td><%= form.date_field :DOB, id:"DOB" %></td>
		<td id="error1"></td>
	</tr>
	<tr>
		<td><%= form.label :salary %></td>
		<td><%= form.text_field :salary, id:"salary" %></td>
		<td id="error2"></td>
	</tr>
	<tr>
		<td><%= form.label :designation %></td>
		<td><%= form.text_field :designation, id:"designation" %></td>
		<td id="error3"></td>
	</tr>
	<tr>
    <td colspan="3"><%= form.submit %></td>
	</tr>
	<tr>
	<td colspan="3"><%= link_to 'Back', employees_path %></td>
</table>
</div>
<% end %>

employeeData/app/views/employees/show.html.erb
<h1>saved successfully</h1>
<p>
<strong>name :</strong>
<%= @employee.name %>
</p>
<p>
<strong>DOB :</strong>
<%= @employee.DOB %>
</p>
<p>
<strong>salary :</strong>
<%= @employee.salary %>
</p>
<p>
<strong>designation :</strong>
<%= @employee.designation %>
</p>
<%= link_to 'Edit',edit_employee_path(@employee) %>
<%= link_to 'Back',employees_path %>
<%= link_to 'list of employee',employees_path %>

employeeData/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeData</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

employeeData/app/views/welcome/index.html.erb
<h1>Welcome to protonshub</h1>
<%= link_to 'My Blog', controller: 'employees' %>
<p>web service provider</p>